// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eInfrastructure.Contexts;

namespace eInfrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220202232658_Push02")]
    partial class Push02
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("eInfrastructure.Entities.Carrito", b =>
                {
                    b.Property<int>("IdCarrito")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DocIDAdamsPay")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("UrlPago")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("IdCarrito");

                    b.HasIndex("IdProducto");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Carrito");
                });

            modelBuilder.Entity("eInfrastructure.Entities.CategoriaProducto", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DescripcionCategoria")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdUsuarioRegistro")
                        .HasColumnType("int");

                    b.HasKey("IdCategoria");

                    b.HasIndex("IdUsuarioRegistro");

                    b.ToTable("CategoriaProducto");
                });

            modelBuilder.Entity("eInfrastructure.Entities.Estado", b =>
                {
                    b.Property<int>("IdEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DescripcionEstado")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("IdEstado");

                    b.ToTable("Estados");

                    b.HasData(
                        new
                        {
                            IdEstado = 1,
                            DescripcionEstado = "USUARIO ACTIVO"
                        },
                        new
                        {
                            IdEstado = 2,
                            DescripcionEstado = "USUARIO BLOQUEADO"
                        },
                        new
                        {
                            IdEstado = 99,
                            DescripcionEstado = "USUARIO BORRADO"
                        });
                });

            modelBuilder.Entity("eInfrastructure.Entities.EstadoProducto", b =>
                {
                    b.Property<int>("IdEstadoProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DescripcionProducto")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("IdEstadoProducto");

                    b.ToTable("EstadosProductos");

                    b.HasData(
                        new
                        {
                            IdEstadoProducto = 1,
                            DescripcionProducto = "ACTIVO"
                        },
                        new
                        {
                            IdEstadoProducto = 2,
                            DescripcionProducto = "INACTIVO"
                        },
                        new
                        {
                            IdEstadoProducto = 99,
                            DescripcionProducto = "BORRADO"
                        });
                });

            modelBuilder.Entity("eInfrastructure.Entities.Notificaciones", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Ambiente")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("FechaNotificacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IdAplicacion")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("IdComercio")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("IdNotificacion")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("TipoNotificacion")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdNotificacion")
                        .IsUnique();

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("eInfrastructure.Entities.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DescripcionProducto")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int");

                    b.Property<int>("IdEstadoProducto")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuarioRegistro")
                        .HasColumnType("int");

                    b.Property<string>("ImagenProducto")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("NombreProducto")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<double>("Precio")
                        .HasColumnType("double");

                    b.HasKey("IdProducto");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdEstadoProducto");

                    b.HasIndex("IdUsuarioRegistro");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("eInfrastructure.Entities.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdEstado")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuarioRegistro")
                        .HasColumnType("int");

                    b.Property<string>("IdiomaElegido")
                        .IsRequired()
                        .HasColumnType("varchar(3) CHARACTER SET utf8mb4")
                        .HasMaxLength(3);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("esAdministrador")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Cedula")
                        .IsUnique();

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("IdEstado");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            IdUsuario = 1,
                            Cedula = "ADM001",
                            Contraseña = "$2a$11$Gdoe/PxT6smTyAoThD0rDOwm6NWRm0Cx4kkCDu7Tbyg4JsVe1xsYS",
                            Correo = "vicram10@gmail.com",
                            FechaRegistro = new DateTime(2022, 2, 2, 20, 26, 58, 110, DateTimeKind.Local).AddTicks(5252),
                            IdEstado = 1,
                            IdUsuarioRegistro = 1,
                            IdiomaElegido = "ES",
                            Nombre = "ADMINISTRADOR GENERAL",
                            esAdministrador = true
                        });
                });

            modelBuilder.Entity("eInfrastructure.Entities.Carrito", b =>
                {
                    b.HasOne("eInfrastructure.Entities.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eInfrastructure.Entities.Usuario", "UsuarioSolicito")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("eInfrastructure.Entities.CategoriaProducto", b =>
                {
                    b.HasOne("eInfrastructure.Entities.Usuario", "UsuarioRegistro")
                        .WithMany()
                        .HasForeignKey("IdUsuarioRegistro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("eInfrastructure.Entities.Producto", b =>
                {
                    b.HasOne("eInfrastructure.Entities.CategoriaProducto", "Categoria")
                        .WithMany()
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eInfrastructure.Entities.EstadoProducto", "EstadoProducto")
                        .WithMany()
                        .HasForeignKey("IdEstadoProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eInfrastructure.Entities.Usuario", "UsuarioRegistro")
                        .WithMany()
                        .HasForeignKey("IdUsuarioRegistro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("eInfrastructure.Entities.Usuario", b =>
                {
                    b.HasOne("eInfrastructure.Entities.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
